/**
 * cursed -- standalone LuaJIT binary wrapper
 *
 * Embeds ahead-of-time compiled bytecode and runs it via the LuaJIT C API.
 * Also statically links tree-sitter and bundled language parsers.
 *
 * Lane architecture:
 *   - Main lane: runs in the main thread (termbox, rendering, piece table writes)
 *   - IO lane: runs in its own pthread + lua_State (file I/O, mmap)
 *   - Communication via lock-free ring buffers in SharedState
 *
 * Build with: just build   (produces a static binary)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>

#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>
#include <luajit.h>

/* Auto-generated bytecode headers */
#include "includes.inc"

/* Bundled tree-sitter + parser declarations */
#include "vendor.h"

/* Shared state between lanes */
#include "shared_state.h"

/* Buffer data model (needs buffer_cleanup compiled in) */
#include "buffer.h"

/* ── Global shared state ─────────────────────────────────────────── */

struct SharedState *g_shared_state;

/* ── Module table (auto-generated) ──────────────────────────────── */

static const struct {
    const char *name;
    const char *bytecode;
    size_t      bytecode_len;
} modules[] = {
#include "modules.inc"
    { NULL, NULL, 0 }
};

/* ── Preload ─────────────────────────────────────────────────────── */

static int preload_modules(lua_State *L)
{
    lua_getglobal(L, "package");
    lua_getfield(L, -1, "preload");

    for (int i = 0; modules[i].name != NULL; i++) {
        int status = luaL_loadbuffer(
            L,
            modules[i].bytecode,
            modules[i].bytecode_len,
            modules[i].name
        );
        if (status != LUA_OK) {
            fprintf(stderr, "cursed: failed to preload %s: %s\n",
                    modules[i].name, lua_tostring(L, -1));
            lua_pop(L, 1);
            continue;
        }
        lua_setfield(L, -2, modules[i].name);
    }

    lua_pop(L, 2); /* pop preload and package */
    return 0;
}

/* ── Lane setup ──────────────────────────────────────────────────── */

static lua_State *create_lane_state(void)
{
    lua_State *L = luaL_newstate();
    if (L == NULL) {
        fprintf(stderr, "cursed: failed to create Lua state\n");
        return NULL;
    }
    luaL_openlibs(L);
    preload_modules(L);
    return L;
}

static void setup_lane_globals(lua_State *L, int argc, char *argv[])
{
    /* Push argv as the global "arg" */
    lua_createtable(L, argc, 1);
    for (int i = 0; i < argc; i++) {
        lua_pushstring(L, argv[i]);
        lua_rawseti(L, -2, i);
    }
    lua_setglobal(L, "arg");


}

/* ── Find entry point ────────────────────────────────────────────── */

static const char *find_module(const char *name, size_t *out_len)
{
    for (int i = 0; modules[i].name != NULL; i++) {
        if (strcmp(modules[i].name, name) == 0) {
            *out_len = modules[i].bytecode_len;
            return modules[i].bytecode;
        }
    }
    return NULL;
}

/* ── IO lane thread ──────────────────────────────────────────────── */

struct IOLaneArgs {
    lua_State *L;
};

static void *io_lane_thread(void *arg)
{
    struct IOLaneArgs *io_args = (struct IOLaneArgs *)arg;
    lua_State *L = io_args->L;
    free(io_args);

    size_t mod_len = 0;
    const char *mod_bc = find_module("cursed.io_lane", &mod_len);

    if (mod_bc == NULL) {
        fprintf(stderr, "cursed: io_lane module not found\n");
        return NULL;
    }

    int status = luaL_loadbuffer(L, mod_bc, mod_len, "cursed.io_lane");
    if (status != LUA_OK) {
        fprintf(stderr, "cursed: io_lane: failed to load bytecode: %s\n",
                lua_tostring(L, -1));
        return NULL;
    }

    status = lua_pcall(L, 0, 0, 0);
    if (status != LUA_OK) {
        fprintf(stderr, "cursed: io_lane: runtime error: %s\n",
                lua_tostring(L, -1));
        return NULL;
    }

    return NULL;
}

/* ── Highlight lane thread ───────────────────────────────────────── */

static void *highlight_lane_thread(void *arg)
{
    struct IOLaneArgs *hl_args = (struct IOLaneArgs *)arg;
    lua_State *L = hl_args->L;
    free(hl_args);

    size_t mod_len = 0;
    const char *mod_bc = find_module("cursed.highlight_lane", &mod_len);

    if (mod_bc == NULL) {
        fprintf(stderr, "cursed: highlight_lane module not found\n");
        return NULL;
    }

    int status = luaL_loadbuffer(L, mod_bc, mod_len, "cursed.highlight_lane");
    if (status != LUA_OK) {
        fprintf(stderr, "cursed: highlight_lane: failed to load bytecode: %s\n",
                lua_tostring(L, -1));
        return NULL;
    }

    status = lua_pcall(L, 0, 0, 0);
    if (status != LUA_OK) {
        fprintf(stderr, "cursed: highlight_lane: runtime error: %s\n",
                lua_tostring(L, -1));
        return NULL;
    }

    return NULL;
}

/* ── Run main lane ───────────────────────────────────────────────── */

static int run_main(lua_State *L)
{
    size_t main_len = 0;
    const char *main_bc = find_module("main", &main_len);

    if (main_bc == NULL) {
        fprintf(stderr, "cursed: no main module found\n");
        return -1;
    }

    int status = luaL_loadbuffer(L, main_bc, main_len, "cursed");
    if (status != LUA_OK) {
        fprintf(stderr, "cursed: failed to load bytecode: %s\n", lua_tostring(L, -1));
        return -1;
    }

    status = lua_pcall(L, 0, 1, 0);
    if (status != LUA_OK) {
        fprintf(stderr, "cursed: runtime error: %s\n", lua_tostring(L, -1));
        return -1;
    }

    if (lua_isnumber(L, -1))
        return (int)lua_tointeger(L, -1);

    return 0;
}

/* ── Entry ───────────────────────────────────────────────────────── */

int main(int argc, char *argv[])
{
    /* Allocate shared state (creates kqueues for each ring buffer) */
    g_shared_state = shared_state_alloc();
    if (g_shared_state == NULL) {
        fprintf(stderr, "cursed: failed to allocate shared state\n");
        return EXIT_FAILURE;
    }

    /* Create IO lane state + thread */
    lua_State *io_L = create_lane_state();
    if (io_L == NULL) return EXIT_FAILURE;
    /* IO lane doesn't get argv — it loads files on request from main */
    setup_lane_globals(io_L, 0, NULL);

    struct IOLaneArgs *io_args = malloc(sizeof(*io_args));
    io_args->L = io_L;

    pthread_t io_thread;
    int rc = pthread_create(&io_thread, NULL, io_lane_thread, io_args);
    if (rc != 0) {
        fprintf(stderr, "cursed: failed to create IO lane thread\n");
        lua_close(io_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }

    /* Create highlight lane state + thread */
    lua_State *hl_L = create_lane_state();
    if (hl_L == NULL) {
        pthread_cancel(io_thread);
        pthread_join(io_thread, NULL);
        lua_close(io_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }
    setup_lane_globals(hl_L, 0, NULL);

    struct IOLaneArgs *hl_args = malloc(sizeof(*hl_args));
    hl_args->L = hl_L;

    pthread_t hl_thread;
    rc = pthread_create(&hl_thread, NULL, highlight_lane_thread, hl_args);
    if (rc != 0) {
        fprintf(stderr, "cursed: failed to create highlight lane thread\n");
        lua_close(hl_L);
        pthread_cancel(io_thread);
        pthread_join(io_thread, NULL);
        lua_close(io_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }

    /* Create main lane state */
    lua_State *main_L = create_lane_state();
    if (main_L == NULL) {
        pthread_cancel(io_thread);
        pthread_join(io_thread, NULL);
        lua_close(io_L);
        pthread_cancel(hl_thread);
        pthread_join(hl_thread, NULL);
        lua_close(hl_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }
    setup_lane_globals(main_L, argc, argv);

    /* Run main lane (blocks until editor exits) */
    int exit_code = run_main(main_L);

    /* Cleanup */
    lua_close(main_L);
    pthread_join(io_thread, NULL);
    lua_close(io_L);
    pthread_join(hl_thread, NULL);
    lua_close(hl_L);

    /* Free shared state (orig.data munmap'd by main lane before exit) */
    shared_state_free(g_shared_state);

    /* Clear the global so stale pointers are visible */
    g_shared_state = NULL;

    return exit_code < 0 ? EXIT_FAILURE : exit_code;
}
