/**
 * cursed -- standalone LuaJIT binary wrapper
 *
 * Embeds ahead-of-time compiled bytecode and runs it via the LuaJIT C API.
 * Also statically links tree-sitter and bundled language parsers.
 *
 * Lane architecture:
 *   - Main lane: runs in the main thread (termbox, rendering, piece table writes)
 *   - IO lane: runs in its own pthread + lua_State (file I/O, mmap)
 *   - Highlight lane: runs in its own pthread + lua_State (tree-sitter parse + query)
 *   - LSP lane: runs in its own pthread + lua_State (subprocess mgmt + JSON-RPC
 *     framing + JSON decode/encode, so heavy JSON never runs on main)
 *   - Communication via lock-free ring buffers in SharedState
 *
 * Build with: just build   (produces a static binary)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>

#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>
#include <luajit.h>

/* Auto-generated bytecode headers */
#include "includes.inc"

/* Bundled tree-sitter + parser declarations */
#include "vendor.h"

/* Shared state between lanes */
#include "shared_state.h"

/* Buffer data model (needs buffer_cleanup compiled in) */
#include "buffer.h"

/* ── Global shared state ─────────────────────────────────────────── */

struct SharedState *g_shared_state;

/* ── Module table (auto-generated) ──────────────────────────────── */

static const struct {
    const char *name;
    const char *bytecode;
    size_t      bytecode_len;
} modules[] = {
#include "modules.inc"
    { NULL, NULL, 0 }
};

/* ── Preload ─────────────────────────────────────────────────────── */

static int preload_modules(lua_State *L)
{
    lua_getglobal(L, "package");
    lua_getfield(L, -1, "preload");

    for (int i = 0; modules[i].name != NULL; i++) {
        int status = luaL_loadbuffer(
            L,
            modules[i].bytecode,
            modules[i].bytecode_len,
            modules[i].name
        );
        if (status != LUA_OK) {
            fprintf(stderr, "cursed: failed to preload %s: %s\n",
                    modules[i].name, lua_tostring(L, -1));
            lua_pop(L, 1);
            continue;
        }
        lua_setfield(L, -2, modules[i].name);
    }

    lua_pop(L, 2); /* pop preload and package */
    return 0;
}

/* ── Lane setup ──────────────────────────────────────────────────── */

static lua_State *create_lane_state(void)
{
    lua_State *L = luaL_newstate();
    if (L == NULL) {
        fprintf(stderr, "cursed: failed to create Lua state\n");
        return NULL;
    }
    luaL_openlibs(L);
    preload_modules(L);
    return L;
}

static void setup_lane_globals(lua_State *L, int argc, char *argv[])
{
    /* Push argv as the global "arg" */
    lua_createtable(L, argc, 1);
    for (int i = 0; i < argc; i++) {
        lua_pushstring(L, argv[i]);
        lua_rawseti(L, -2, i);
    }
    lua_setglobal(L, "arg");


}

/* ── Find entry point ────────────────────────────────────────────── */

static const char *find_module(const char *name, size_t *out_len)
{
    for (int i = 0; modules[i].name != NULL; i++) {
        if (strcmp(modules[i].name, name) == 0) {
            *out_len = modules[i].bytecode_len;
            return modules[i].bytecode;
        }
    }
    return NULL;
}

/* ── IO lane thread ──────────────────────────────────────────────── */

/* ── Lane thread (single entry for all worker lanes) ─────────────── */

struct LaneThreadArgs {
    lua_State  *L;
    const char *module;  /* e.g. "cursed.io_lane" */
};

static void *lane_thread(void *arg)
{
    struct LaneThreadArgs *args = (struct LaneThreadArgs *)arg;
    lua_State *L = args->L;
    const char *module = args->module;
    free(args);

    size_t mod_len = 0;
    const char *mod_bc = find_module(module, &mod_len);

    if (mod_bc == NULL) {
        fprintf(stderr, "cursed: %s module not found\n", module);
        return NULL;
    }

    int status = luaL_loadbuffer(L, mod_bc, mod_len, module);
    if (status != LUA_OK) {
        fprintf(stderr, "cursed: %s: failed to load bytecode: %s\n",
                module, lua_tostring(L, -1));
        return NULL;
    }

    status = lua_pcall(L, 0, 0, 0);
    if (status != LUA_OK) {
        fprintf(stderr, "cursed: %s: runtime error: %s\n",
                module, lua_tostring(L, -1));
        return NULL;
    }

    return NULL;
}

/* ── Lane restart (FFI-callable) ──────────────────────────────── */

void restart_lane_thread(uint8_t lane_idx)
{
    static const char *lane_modules[] = {
        "cursed.io_lane",
        "cursed.highlight_lane",
        "cursed.lsp_lane",
        "cursed.proc_lane",
        "cursed.task_lane"
    };

    if (lane_idx > 4) {
        fprintf(stderr, "cursed: restart_lane_thread: invalid lane index %u\n", lane_idx);
        return;
    }

    lua_State *L = create_lane_state();
    if (L == NULL) return;

    setup_lane_globals(L, 0, NULL);

    struct LaneThreadArgs *args = malloc(sizeof(*args));
    if (args == NULL) {
        lua_close(L);
        return;
    }
    args->L = L;
    args->module = lane_modules[lane_idx];

    pthread_t thread;
    int rc = pthread_create(&thread, NULL, lane_thread, args);
    if (rc != 0) {
        fprintf(stderr, "cursed: failed to restart lane %u thread\n", lane_idx);
        lua_close(L);
        free(args);
        return;
    }

    pthread_detach(thread);
}

static int run_main(lua_State *L)
{
    size_t main_len = 0;
    const char *main_bc = find_module("main", &main_len);

    if (main_bc == NULL) {
        fprintf(stderr, "cursed: no main module found\n");
        return -1;
    }

    int status = luaL_loadbuffer(L, main_bc, main_len, "cursed");
    if (status != LUA_OK) {
        fprintf(stderr, "cursed: failed to load bytecode: %s\n", lua_tostring(L, -1));
        return -1;
    }

    status = lua_pcall(L, 0, 1, 0);
    if (status != LUA_OK) {
        fprintf(stderr, "cursed: runtime error: %s\n", lua_tostring(L, -1));
        return -1;
    }

    if (lua_isnumber(L, -1))
        return (int)lua_tointeger(L, -1);

    return 0;
}

/* ── Entry ───────────────────────────────────────────────────────── */

int main(int argc, char *argv[])
{
    /* Allocate shared state (creates kqueues for each ring buffer) */
    g_shared_state = shared_state_alloc();
    if (g_shared_state == NULL) {
        fprintf(stderr, "cursed: failed to allocate shared state\n");
        return EXIT_FAILURE;
    }

    /* Create IO lane state + thread */
    lua_State *io_L = create_lane_state();
    if (io_L == NULL) return EXIT_FAILURE;
    /* IO lane doesn't get argv — it loads files on request from main */
    setup_lane_globals(io_L, 0, NULL);

    struct LaneThreadArgs *io_args = malloc(sizeof(*io_args));
    io_args->L = io_L;
    io_args->module = "cursed.io_lane";

    pthread_t io_thread;
    int rc = pthread_create(&io_thread, NULL, lane_thread, io_args);
    if (rc != 0) {
        fprintf(stderr, "cursed: failed to create IO lane thread\n");
        lua_close(io_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }

    /* Create highlight lane state + thread */
    lua_State *hl_L = create_lane_state();
    if (hl_L == NULL) {
        pthread_cancel(io_thread);
        pthread_join(io_thread, NULL);
        lua_close(io_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }
    setup_lane_globals(hl_L, 0, NULL);

    struct LaneThreadArgs *hl_args = malloc(sizeof(*hl_args));
    hl_args->L = hl_L;
    hl_args->module = "cursed.highlight_lane";

    pthread_t hl_thread;
    rc = pthread_create(&hl_thread, NULL, lane_thread, hl_args);
    if (rc != 0) {
        fprintf(stderr, "cursed: failed to create highlight lane thread\n");
        lua_close(hl_L);
        pthread_cancel(io_thread);
        pthread_join(io_thread, NULL);
        lua_close(io_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }

    /* Create LSP lane state + thread (owns subprocess mgmt + JSON-RPC framing
     * + JSON decode/encode so heavy JSON never runs on the main thread). */
    lua_State *lsp_L = create_lane_state();
    if (lsp_L == NULL) {
        pthread_cancel(io_thread);
        pthread_join(io_thread, NULL);
        lua_close(io_L);
        pthread_cancel(hl_thread);
        pthread_join(hl_thread, NULL);
        lua_close(hl_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }
    setup_lane_globals(lsp_L, 0, NULL);

    struct LaneThreadArgs *lsp_args = malloc(sizeof(*lsp_args));
    lsp_args->L = lsp_L;
    lsp_args->module = "cursed.lsp_lane";

    pthread_t lsp_thread;
    rc = pthread_create(&lsp_thread, NULL, lane_thread, lsp_args);
    if (rc != 0) {
        fprintf(stderr, "cursed: failed to create LSP lane thread\n");
        lua_close(lsp_L);
        pthread_cancel(io_thread);
        pthread_join(io_thread, NULL);
        lua_close(io_L);
        pthread_cancel(hl_thread);
        pthread_join(hl_thread, NULL);
        lua_close(hl_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }

    /* Create proc lane state + thread (general subprocess control,
     * shape-agnostic: no JSON-RPC framing, owns arbitrary children with
     * stdout/stderr pipes registered on its own kqueue). */
    lua_State *proc_L = create_lane_state();
    if (proc_L == NULL) {
        pthread_cancel(io_thread);
        pthread_join(io_thread, NULL);
        lua_close(io_L);
        pthread_cancel(hl_thread);
        pthread_join(hl_thread, NULL);
        lua_close(hl_L);
        pthread_cancel(lsp_thread);
        pthread_join(lsp_thread, NULL);
        lua_close(lsp_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }
    setup_lane_globals(proc_L, 0, NULL);

    struct LaneThreadArgs *proc_args = malloc(sizeof(*proc_args));
    proc_args->L = proc_L;
    proc_args->module = "cursed.proc_lane";

    pthread_t proc_thread;
    rc = pthread_create(&proc_thread, NULL, lane_thread, proc_args);
    if (rc != 0) {
        fprintf(stderr, "cursed: failed to create proc lane thread\n");
        lua_close(proc_L);
        pthread_cancel(io_thread);
        pthread_join(io_thread, NULL);
        lua_close(io_L);
        pthread_cancel(hl_thread);
        pthread_join(hl_thread, NULL);
        lua_close(hl_L);
        pthread_cancel(lsp_thread);
        pthread_join(lsp_thread, NULL);
        lua_close(lsp_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }

    /* Create task lane state + thread (off-thread bytecode evaluation:
     * runs string.dump'd functions with JSON args, returns JSON results). */
    lua_State *task_L = create_lane_state();
    if (task_L == NULL) {
        pthread_cancel(io_thread);
        pthread_join(io_thread, NULL);
        lua_close(io_L);
        pthread_cancel(hl_thread);
        pthread_join(hl_thread, NULL);
        lua_close(hl_L);
        pthread_cancel(lsp_thread);
        pthread_join(lsp_thread, NULL);
        lua_close(lsp_L);
        pthread_cancel(proc_thread);
        pthread_join(proc_thread, NULL);
        lua_close(proc_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }
    setup_lane_globals(task_L, 0, NULL);

    struct LaneThreadArgs *task_args = malloc(sizeof(*task_args));
    task_args->L = task_L;
    task_args->module = "cursed.task_lane";

    pthread_t task_thread;
    rc = pthread_create(&task_thread, NULL, lane_thread, task_args);
    if (rc != 0) {
        fprintf(stderr, "cursed: failed to create task lane thread\n");
        lua_close(task_L);
        pthread_cancel(io_thread);
        pthread_join(io_thread, NULL);
        lua_close(io_L);
        pthread_cancel(hl_thread);
        pthread_join(hl_thread, NULL);
        lua_close(hl_L);
        pthread_cancel(lsp_thread);
        pthread_join(lsp_thread, NULL);
        lua_close(lsp_L);
        pthread_cancel(proc_thread);
        pthread_join(proc_thread, NULL);
        lua_close(proc_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }

    /* Create main lane state */
    lua_State *main_L = create_lane_state();
    if (main_L == NULL) {
        pthread_cancel(io_thread);
        pthread_join(io_thread, NULL);
        lua_close(io_L);
        pthread_cancel(hl_thread);
        pthread_join(hl_thread, NULL);
        lua_close(hl_L);
        pthread_cancel(lsp_thread);
        pthread_join(lsp_thread, NULL);
        lua_close(lsp_L);
        pthread_cancel(task_thread);
        pthread_join(task_thread, NULL);
        lua_close(task_L);
        pthread_cancel(proc_thread);
        pthread_join(proc_thread, NULL);
        lua_close(proc_L);
        shared_state_free(g_shared_state);
        return EXIT_FAILURE;
    }
    setup_lane_globals(main_L, argc, argv);

    /* Run main lane (blocks until editor exits) */
    int exit_code = run_main(main_L);

    /* Cleanup.
     *
     * The worker lanes (IO/highlight/LSP/proc/task) block in kevent() waiting for
     * work. In the normal TUI exit path, main has already set
     * running=false and poked the lane wake-idents so each lane spins
     * once, observes running=false, and returns — pthread_join then
     * reaps a clean exit. In the HEADLESS path (-e/-l/-h), main returns
     * before the TUI ever starts, so the lanes are still parked in
     * kevent() and a plain pthread_join would block forever. Detect that
     * (running already false) and cancel-join instead. Cancellation is
     * safe here: we tear down every Lua state + the shared state
     * immediately after, so any in-flight lane work is discarded along
     * with its state. */
    int lanes_already_stopped = (g_shared_state != NULL && !g_shared_state->running);
    lua_close(main_L);
    if (lanes_already_stopped) {
        pthread_cancel(io_thread);
    }
    pthread_join(io_thread, NULL);
    lua_close(io_L);
    if (lanes_already_stopped) {
        pthread_cancel(hl_thread);
    }
    pthread_join(hl_thread, NULL);
    lua_close(hl_L);
    if (lanes_already_stopped) {
        pthread_cancel(lsp_thread);
    }
    pthread_join(lsp_thread, NULL);
    lua_close(lsp_L);
    if (lanes_already_stopped) {
        pthread_cancel(proc_thread);
    }
    pthread_join(proc_thread, NULL);
    lua_close(proc_L);
    if (lanes_already_stopped) {
        pthread_cancel(task_thread);
    }
    pthread_join(task_thread, NULL);
    lua_close(task_L);

    /* Free shared state (orig.data munmap'd by main lane before exit) */
    shared_state_free(g_shared_state);

    /* Clear the global so stale pointers are visible */
    g_shared_state = NULL;

    return exit_code < 0 ? EXIT_FAILURE : exit_code;
}
